"""Tests for the scripts that read a repository: snapshot, loc_count and git_stats."""
from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

from helpers import SCRIPTS, commit, git, new_repo, run_script, write


class SnapshotTest(unittest.TestCase):
    def test_records_head_counts_and_dates(self):
        tmp, repo = new_repo()
        with tmp:
            commit(repo, "first", {"a.txt": "a\n"}, date="2026-01-01T10:00:00+00:00")
            commit(repo, "second", {"b.txt": "b\n"}, date="2026-01-02T10:00:00+00:00")
            git(repo, "tag", "v1.0.0")
            out = run_script("snapshot.py", str(repo))
            self.assertEqual(out["head"], git(repo, "rev-parse", "HEAD").strip())
            self.assertEqual(out["commits_on_head"], 2)
            self.assertEqual(out["tags"], 1)
            self.assertTrue(out["first_commit_date"].startswith("2026-01-01"))
            self.assertFalse(out["local_changes"])

    def test_flags_shallow_and_partial_clones(self):
        tmp, repo = new_repo()
        with tmp:
            for n in range(3):
                commit(repo, f"c{n}", {"f.txt": f"{n}\n"})
            git(repo, "config", "uploadpack.allowfilter", "true")
            base = Path(tmp.name)
            git(base, "clone", "-q", "--depth", "1", f"file://{repo}", "shallow")
            git(base, "clone", "-q", "--filter=blob:none", f"file://{repo}", "partial")
            shallow = run_script("snapshot.py", str(base / "shallow"))
            self.assertTrue(shallow["shallow"])
            self.assertEqual(shallow["commits_on_head"], 1)
            partial = run_script("snapshot.py", str(base / "partial"))
            self.assertEqual(partial["partial_clone_filter"], "blob:none")
            self.assertEqual(len(partial["warnings"]), 1)
            full = run_script("snapshot.py", str(repo))
            self.assertEqual((full["shallow"], full["partial_clone_filter"], full["warnings"]), (False, None, []))

    def test_refuses_a_folder_that_is_not_a_repository(self):
        with tempfile.TemporaryDirectory() as folder:
            import subprocess, sys
            result = subprocess.run([sys.executable, str(SCRIPTS / "snapshot.py"), folder], capture_output=True, text=True)
            self.assertNotEqual(result.returncode, 0)


class LocCountTest(unittest.TestCase):
    def test_splits_source_test_generated_and_skips_dependencies(self):
        with tempfile.TemporaryDirectory() as folder:
            root = Path(folder)
            write(root, "src/app.ts", "const a = 1;\n\nexport default a;\n")
            write(root, "src/app.test.ts", "test('a', () => {});\n")
            write(root, "tests/test_tool.py", "def test_x():\n    pass\n")
            write(root, "src/api_pb2.py", "x = 1\n")
            write(root, "src/client.ts", "// @generated by a tool\nexport {};\n")
            write(root, "node_modules/lib/index.js", "a\nb\nc\nd\n")
            write(root, "vendor/x.go", "package x\n")
            out = run_script("loc_count.py", folder)
            totals = out["totals"]
            self.assertEqual(totals["source"]["files"], 1)
            self.assertEqual(totals["source"]["lines"], 3)
            self.assertEqual(totals["source"]["non_blank"], 2)
            self.assertEqual(totals["test"]["files"], 2)
            self.assertEqual(totals["generated"]["files"], 2)
            languages = {row["language"] for row in out["languages"]}
            self.assertNotIn("Go", languages)

    def test_counts_an_older_commit_without_touching_the_clone(self):
        tmp, repo = new_repo()
        with tmp:
            commit(repo, "small", {"main.py": "a = 1\n"})
            old = git(repo, "rev-parse", "HEAD").strip()
            commit(repo, "bigger", {"main.py": "a = 1\nb = 2\nc = 3\n"})
            out = run_script("loc_count.py", str(repo), "--at", old)
            self.assertEqual(out["totals"]["source"]["lines"], 1)
            self.assertEqual((repo / "main.py").read_text(), "a = 1\nb = 2\nc = 3\n")
            self.assertEqual(git(repo, "status", "--porcelain"), "")


class GitStatsTest(unittest.TestCase):
    def test_authors_fixes_releases_and_ai_signals(self):
        signals = json.loads((SCRIPTS / "ai_signals.json").read_text())
        trailer = signals["trailer_keys"][0]
        assistant = signals["assistants"][0]
        instruction = next(f for f in signals["instruction_files"] if not f.endswith("/"))
        tmp, repo = new_repo()
        with tmp:
            commit(repo, "Add feature", {"a.py": "1\n"}, name="Grace", email="grace@example.com", date="2026-03-02T10:00:00+00:00")
            git(repo, "tag", "v0.1.0")
            commit(repo, "fix: crash on start", {"a.py": "2\n"}, name="Grace", email="grace@example.com", date="2026-03-03T10:00:00+00:00")
            commit(repo, f"Improve docs\n\n{trailer}: {assistant['example']}", {"b.md": "x\n", instruction: "rules\n"},
                   name="Bob", email="bob@example.com", date="2026-03-10T10:00:00+00:00")
            commit(repo, "Tidy", {"a.py": "3\n"}, name="Grace Hopper", email="12345+grace@users.noreply.github.com", date="2026-03-11T10:00:00+00:00")
            git(repo, "tag", "v0.2.0")
            out = run_script("git_stats.py", str(repo))
            self.assertEqual(out["commits"]["non_merge"], 4)
            self.assertEqual(out["fixes"]["non_merge_fix_commits"], 1)
            self.assertEqual(out["releases"]["version_tags"], 2)
            self.assertEqual(out["ai_assisted"]["non_merge_commits_with_assistant_trailer"], 1)
            self.assertEqual(out["ai_assisted"]["by_assistant"], {assistant["label"]: 1})
            self.assertIn(instruction, out["ai_assisted"]["agent_instruction_files_at_head"])
            self.assertEqual(out["hotspots"][0], {"path": "a.py", "commits": 3})
            weeks = {w["week"] for w in out["weekly"]}
            self.assertEqual(weeks, {"2026-W10", "2026-W11"})
            names = [set(group["names"]) for group in out["authors"]["possible_same_person"]]
            self.assertIn({"Grace", "Grace Hopper"}, names)

    def test_every_assistant_example_matches_its_own_label(self):
        import re
        signals = json.loads((SCRIPTS / "ai_signals.json").read_text())
        for assistant in signals["assistants"]:
            patterns = [re.compile(p, re.I) for p in assistant["patterns"]]
            self.assertTrue(any(p.search(assistant["example"]) for p in patterns), assistant["label"])


if __name__ == "__main__":
    unittest.main()
