#!/usr/bin/env python3
"""Count lines of source, test and generated code, by area and by language.

Usage:
  python3 loc_count.py <repo-or-folder> [--at <git-rev>] [--depth 1] [--exclude DIR ...] [--top 15]

--at counts the tree of an older commit or tag. The tree is read with `git archive` into a
temporary folder, so the working clone is never touched. Run it at a few dates to show growth;
for a date, pass the last commit before it: --at "$(git -C <repo> rev-list -1 --before=2026-09-01 HEAD)".
Do not use reflog syntax such as HEAD@{date}: a fresh clone has no reflog for past dates.

Dependency, build and vendored folders are skipped (see SKIP_DIRS in common.py); add your own
with --exclude. A file is a test when its path or name says so, and generated when its first
lines carry a generator marker or its name is a known generated pattern. Prints JSON with
totals, rows per area and per language, the largest source files and the rules applied.
"""
from __future__ import annotations

import argparse
import io
import re
import subprocess
import sys
import tarfile
import tempfile
from collections import defaultdict
from pathlib import Path

from common import SKIP_DIRS, is_binary, is_git_repo, iter_files, print_json, rel

LANGUAGES = {
    ".py": "Python", ".pyi": "Python", ".js": "JavaScript", ".mjs": "JavaScript", ".cjs": "JavaScript",
    ".jsx": "JavaScript", ".ts": "TypeScript", ".tsx": "TypeScript", ".mts": "TypeScript", ".cts": "TypeScript",
    ".go": "Go", ".rs": "Rust", ".java": "Java", ".kt": "Kotlin", ".kts": "Kotlin", ".scala": "Scala",
    ".swift": "Swift", ".m": "Objective-C", ".mm": "Objective-C", ".c": "C", ".h": "C/C++ header",
    ".cc": "C++", ".cpp": "C++", ".cxx": "C++", ".hpp": "C++", ".hh": "C++", ".cs": "C#", ".fs": "F#",
    ".rb": "Ruby", ".php": "PHP", ".dart": "Dart", ".ex": "Elixir", ".exs": "Elixir", ".erl": "Erlang",
    ".clj": "Clojure", ".hs": "Haskell", ".lua": "Lua", ".r": "R", ".jl": "Julia", ".zig": "Zig",
    ".vue": "Vue", ".svelte": "Svelte", ".astro": "Astro", ".css": "CSS", ".scss": "CSS", ".sass": "CSS",
    ".less": "CSS", ".html": "HTML", ".sql": "SQL", ".sh": "Shell", ".bash": "Shell", ".zsh": "Shell",
    ".ps1": "PowerShell", ".proto": "Protocol Buffers", ".graphql": "GraphQL", ".sol": "Solidity",
    ".tf": "Terraform", ".nix": "Nix", ".gd": "GDScript",
}

TEST_PATH = re.compile(
    r"(^|/)(__tests__|__test__|tests?|testing|spec|specs|e2e|integration[-_]tests?|androidTest|"
    r"test[-_]?fixtures|fixtures|testdata|test_data|mocks?|__mocks__|[A-Za-z0-9]+Tests|[A-Za-z0-9]+UITests)(/|$)"
)
TEST_NAME = re.compile(
    r"(\.(test|spec|e2e|stories)\.[a-z]+$)|(_test\.(go|py|rs|rb|exs|dart)$)|(^test_.*\.py$)|"
    r"(Tests?\.(swift|kt|java|cs)$)|(_spec\.rb$)|(\.node-test\.mjs$)"
)
GENERATED_NAME = re.compile(
    r"(\.pb\.[a-z]+$)|(_pb2(_grpc)?\.py$)|(\.generated\.[a-z]+$)|(\.g\.dart$)|(\.min\.(js|css)$)|"
    r"(\.bundle\.js$)|(_generated\.[a-z]+$)|(\.designer\.cs$)"
)
GENERATED_MARKER = re.compile(rb"(@generated|auto-?generated|do not edit|code generated by|generated by .{0,40}do not modify)", re.I)


def classify(path: str, head: bytes) -> str:
    name = path.rsplit("/", 1)[-1]
    if GENERATED_NAME.search(name) or GENERATED_MARKER.search(head[:800]):
        return "generated"
    if TEST_PATH.search(path) or TEST_NAME.search(name):
        return "test"
    return "source"


def count(root: Path, depth: int, exclude: set) -> dict:
    totals = {kind: {"files": 0, "lines": 0, "non_blank": 0} for kind in ("source", "test", "generated")}
    areas = defaultdict(lambda: {"source": 0, "test": 0, "generated": 0, "files": 0})
    languages = defaultdict(lambda: {"source": 0, "test": 0, "generated": 0, "files": 0})
    files = []
    for path in iter_files(root, extra_skip=exclude):
        language = LANGUAGES.get(path.suffix.lower())
        if not language:
            continue
        try:
            data = path.read_bytes()
        except OSError:
            continue
        if is_binary(data):
            continue
        relative = rel(path, root)
        kind = classify(relative, data)
        lines = data.count(b"\n") + (1 if data and not data.endswith(b"\n") else 0)
        non_blank = sum(1 for line in data.splitlines() if line.strip())
        totals[kind]["files"] += 1
        totals[kind]["lines"] += lines
        totals[kind]["non_blank"] += non_blank
        parts = relative.split("/")
        area = "/".join(parts[:depth]) if len(parts) > depth else "(root)"
        areas[area][kind] += lines
        areas[area]["files"] += 1
        languages[language][kind] += lines
        languages[language]["files"] += 1
        if kind == "source":
            files.append((lines, relative))
    files.sort(reverse=True)
    return {
        "totals": totals,
        "areas": sorted(({"area": k, **v} for k, v in areas.items()), key=lambda r: -(r["source"] + r["test"])),
        "languages": sorted(({"language": k, **v} for k, v in languages.items()), key=lambda r: -(r["source"] + r["test"])),
        "largest_source_files": [{"path": p, "lines": n} for n, p in files],
    }


def export_tree(repo: Path, rev: str, target: Path) -> None:
    """Write the tree of rev into target with git archive, without touching the clone."""
    archive = subprocess.run(["git", "-C", str(repo), "archive", "--format=tar", rev], capture_output=True)
    if archive.returncode != 0:
        raise RuntimeError(archive.stderr.decode(errors="replace").strip())
    with tarfile.open(fileobj=io.BytesIO(archive.stdout)) as tar:
        safe = [m for m in tar.getmembers() if not (m.name.startswith("/") or ".." in Path(m.name).parts) and (m.isfile() or m.isdir())]
        if hasattr(tarfile, "data_filter"):
            tar.extractall(target, members=safe, filter="data")
        else:
            tar.extractall(target, members=safe)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("root", help="repository or folder to count")
    parser.add_argument("--at", help="git commit or tag to count instead of the working tree (see the note on dates above)")
    parser.add_argument("--depth", type=int, default=1, help="folder depth that defines an area (default 1)")
    parser.add_argument("--exclude", action="append", default=[], help="extra folder name to skip; repeatable")
    parser.add_argument("--top", type=int, default=15, help="how many of the largest source files to list")
    args = parser.parse_args()

    root = Path(args.root)
    exclude = set(args.exclude)
    if args.at:
        if not is_git_repo(root):
            parser.error("--at needs a git repository")
        with tempfile.TemporaryDirectory(prefix="loc-") as tmp:
            export_tree(root, args.at, Path(tmp))
            result = count(Path(tmp), args.depth, exclude)
    else:
        result = count(root, args.depth, exclude)

    result["largest_source_files"] = result["largest_source_files"][: args.top]
    print_json({
        "root": str(root.resolve()),
        "at": args.at or "working tree",
        **result,
        "rules": {
            "skipped_folders": sorted(SKIP_DIRS | exclude),
            "counted_extensions": sorted(LANGUAGES),
            "lines": "physical lines; non_blank excludes empty lines",
            "test": "path segment such as tests/, __tests__/, spec/, fixtures/, or a name such as *.test.*, *_test.go, test_*.py, *Tests.swift",
            "generated": "name such as *.pb.*, *_pb2.py, *.min.js, *.g.dart, or a generator marker in the first 800 bytes",
        },
    })
    return 0


if __name__ == "__main__":
    sys.exit(main())
